services:
  apigateway:
    build: .
    ports:
      - "80:80"
    environment:
      - AUTH_SERVICE_URL=http://localhost:8090/api/
      - PRODUCT_SERVICE_URL=http://localhost:8000/api/v1/
    network_mode: host
